module dls2_interface
{
  module msg
  {
    struct Attitude
    {
      // header
      string frame_id;
      unsigned long sequence_id;
      double timestamp;

      // data
      double orientation[4];
      double angular_velocity[3];
      double euler_angles_estimation[3];
    };
  };
};
