module dls2_interface {
  	module msg {
		struct BlindStateLight
		{
			sequence<double> joints_position;
			sequence<double> joints_velocity;
			sequence<double> joints_acceleration;
			
			sequence<double> joints_temperature;
			sequence<double> joints_current;
		    sequence<double> joints_effort;
		};
  	};
};