#include "JointStatesLight.idl"
#include "Pose.idl"
#include "Screw.idl"
#include "Vec3.idl"

module dls2_interface {
	module msg {
		struct ReferenceLight
		{
			dls2_interface::msg::JointStatesLight joints_state;
			
			sequence<dls2_interface::msg::Vec3> feet_position;
			sequence<dls2_interface::msg::Vec3> feet_forces;

			dls2_interface::msg::Pose base_pose;
			dls2_interface::msg::Screw base_velocity;
		};
	};
};